### ISSUE TITLE
training set

### ISSUE THREAD

**Issue by Fateeeeee** [TolgaBkm/HRPlanes#1]
Hello, is there any training set available?

**Comment by yahuyang** [comment]
I have the same question

**Comment by JiweiTian** [comment]
I also have the same question.

**Comment by TolgaBkm** [comment]
The dataset is now available for download if you are still interested:
https://drive.google.com/drive/folders/1NYji6HWh4HRLQMTagsn4tTv4LOdDrc9P?usp=sharing
